# 01_numpy_intro

In [1]:
import numpy as np

In [2]:
# first array; dtype = datatypes
tablica = np.array([1,2,3], dtype=np.int16)
tablica

array([1, 2, 3], dtype=int16)

In [3]:
#print datatype
print(tablica.dtype) 

int16


In [4]:
d2d = np.array ([[1,2,3],[4,5,6]])
print("d2d: \n", d2d)
print("shape: ", d2d.shape)

d2d: 
 [[1 2 3]
 [4 5 6]]
shape:  (2, 3)


# Array creation

In [5]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.ones([2,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
# Create a constant array ((x,y), number)
np.full((2,3),4)

array([[4, 4, 4],
       [4, 4, 4]])

In [8]:
# (start, stop, step)
np.arange(3,40,3)

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39])

In [9]:
# multiple arrays in one variable
a = np.array([[np.arange(2,30,4)], [np.arange(5,30,5)]])
print(a)

[[array([ 2,  6, 10, 14, 18, 22, 26])]
 [array([ 5, 10, 15, 20, 25])]]


In [10]:
a.shape

(2, 1)

In [11]:
# (start, stop, points)
#  numbers spaced evenly on a lin scale
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [12]:
#  numbers spaced evenly on a log scale
np.logspace(0.5,3,4) 

array([   3.16227766,   21.5443469 ,  146.77992676, 1000.        ])

##  Indexing

In [13]:
# from 0 - (n-1)
a =  np.arange(30) 

In [14]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [15]:
# random numbers
c = np.random.rand(5)
print(c)

[0.18982903 0.96980885 0.66522428 0.06022944 0.73258362]


## Reshape - new shape to an array without changing its data

In [16]:
d = np.arange(20).reshape(4,5) #formatowanie
print(d)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [17]:
# print all in one line
e = d.flatten()
print(e)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [18]:
# Roll array elements along a given axis
f = np.arange(30)
np.roll(f, 15)

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29,  0,  1,
        2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Arithmetic Operations

In [19]:
a = np.arange(10)
b = np.ones(10)

In [20]:
# add
a+b+b

array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [21]:
# multiply
a*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [22]:
# q? : if we divide the signal by some number it will be quieter? 

# Generating sinewave

In [23]:
f = 1000 # frequency our signal
fs = 44100 # sample rate
t = np.arange(-5,5,1./fs) # in every sample 
A = np.power(2,16)/2-1 # amplitude

In [24]:
sinus = A * np.sin(2*np.pi*f*t)

In [25]:
audio_sinus = sinus.astype(np.int16)

In [26]:
audio_sinus[:100] #print first 100 samples

array([     0,   4652,   9211,  13582,  17679,  21417,  24721,  27525,
        29770,  31412,  32418,  32766,  32451,  31478,  29867,  27651,
        24874,  21593,  17875,  13795,   9434,   4883,    233,  -4421,
        -8986, -13370, -17482, -21240, -24568, -27397, -29672, -31345,
       -32383, -32765, -32482, -31542, -29962, -27775, -25025, -21768,
       -18070, -14006,  -9658,  -5114,   -466,   4190,   8762,  13156,
        17284,  21062,  24413,  27269,  29572,  31276,  32346,  32761,
        32512,  31604,  30056,  27898,  25175,  21942,  18264,  14217,
         9881,   5344,    700,  -3958,  -8537, -12942, -17085, -20882,
       -24256, -27138, -29471, -31206, -32308, -32756, -32540, -31665,
       -30148, -28020, -25324, -22115, -18458, -14427, -10103,  -5574,
         -933,   3726,   8311,  12727,  16886,  20702,  24099,  27007,
        29368,  31134,  32269,  32750], dtype=int16)